### ISSUE TITLE
Chart "VALID SHARES REPORTED BY RIG" does no honor selected pool 

### ISSUE THREAD

**Issue by StefanOberhumer** [rodneymo/rig-monitorv2#53]
In the "Mining Overview Dashboard 3.0" the chart "VALID SHARES REPORTED BY RIG" does not honor selected pool (in the left top corner). 
It displays all pools!

**Comment by rodneymo** [comment]
Fixed in attached dashboard export (same as #54)
[Mining Overview Dashboard 3.0-1530688886167.json.zip](https://github.com/rodneymo/rig-monitorv2/files/2162206/Mining.Overview.Dashboard.3.0-1530688886167.json.zip)

**Comment by StefanOberhumer** [comment]
No - Still happens
Query in `"title": "VALID SHARES REPORTED BY RIG",`:


`"query": "SELECT sum(\"valid_shares\") FROM \"autogen\".\"miner_system\" WHERE miner='[[miner]]' and $timeFilter GROUP BY time(1m), rig_id fill(null)",`

**Comment by rodneymo** [comment]
I overlooked this and only fixed the pool shares. Could you try this one for me?
SELECT sum("valid_shares") FROM "autogen"."miner_system" WHERE label='[[pool]]' and miner='[[miner]]' and $timeFilter GROUP BY time(1m), rig_id fill(null)

**Comment by StefanOberhumer** [comment]
:+1: works
